language: python
python:
  - "3.4"
  - "3.5"
install: "pip install -r requirements.txt"
script: "python3 manage.py test"
addons:
  postgresql: "9.4"
before_script:
  - mkdir -p $TRAVIS_BUILD_DIR/logging && touch $TRAVIS_BUILD_DIR/logging/{catalog,django,vrfy,ldap_auth,course}.log
